spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa_db/datajpa
    username: yeran
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging.level:
   org.hibernate.SQL: debug

   org.springframework.jdbc.core.JdbcTemplate: debug
   org.springframework.jdbc.core.StatementCreatorUtils: trace
#   org.hibernate.type: trace
